routes/web.php
	Route::get('/bank_list',['middleware'=>'check-permission:admin|superadmin','uses'=>'BankController@index']);
	Route::get('/bank/create',['middleware'=>'check-permission:admin|superadmin','uses'=>'BankController@create'])->name('bank.add');
	Route::POST('/bank/store',['middleware'=>'check-permission:admin|superadmin','uses'=>'BankController@store'])->name('bank.store');
	Route::get('/all_bank_list',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@all_bank_list']);
    Route::get('/bank_transaction_details/{id}',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@bank_transaction_details'])->name('bank.bank_transaction_details');    
	
	// Cash In (Deposit Money)
    Route::get('/cash_in',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@cash_in'])->name('cash_in');
	Route::POST('/cash_in_store',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@cash_in_store'])->name('bank.cash_in_store');

	// Cash out (Withdrow Money)
    Route::get('/cash_out',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@cash_out'])->name('cash_out');
	Route::POST('/cash_out_store',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@cash_out_store'])->name('bank.cash_out_store');

	Route::get('/transaction_history',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@transaction_history']);
	Route::POST('/transaction_history_data',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@transaction_history_data'])->name('transaction_history_data');

	//Manage Expenses
	Route::resource('expenses', 'ExpensesController');
	Route::get('/expenses',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@index']);
	Route::get('/todays_expense_history',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@todays_expenses']);
	Route::get('/new_expense',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@create']);

	//Manage Expense Category
	Route::resource('expenseCategory', 'ExpenseCategoryController');
	Route::get('/expense_category',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpenseCategoryController@index']);

	//Manage Income Category
	Route::resource('incomeSourceCategory', 'IncomeSourceCategoryController');
	Route::get('/incomes_category',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceCategoryController@index']);


	//Manage Expenses
	Route::resource('incomes', 'IncomeSourceController');
	Route::get('/incomes_delete/{income}',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@show_delete'])->name('incomes.delete');
	Route::get('/incomes',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@index']);
	Route::get('/todays_income_history',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@todays_income']);
	Route::get('/new_incomes',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@create']);

	//Manage Give Loan
	Route::resource('giveLoan', 'giveLoanController');
	Route::get('/give_loan',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@index']);
	Route::POST('/give_new_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@giveNewLoan']);
	Route::POST('/give_return_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@giveReturnLoan']);

	//Manage Receive Loan
	Route::resource('receiveLoan', 'receiveLoanController');
	Route::get('/receive_loan',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@index']);
	Route::POST('/receive_new_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@giveNewLoan']);
	Route::POST('/receive_return_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@giveReturnLoan']);

	//Manage Advance Payment
	Route::resource('advancePayment', 'advancePaymentController');
	Route::get('/manage_advance_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@index']);
	Route::POST('/advance_new_expense',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@advanceNewExpense']);
	Route::POST('/give_new_advance_amount',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@advanceNewPayment']);

	//Manage Bill Code
	Route::resource('billcodes', 'billcodeController');
	Route::get('/generate_bill_code',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@create']);
	Route::get('/bill_code_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@index']);
    Route::get('/barcode_pdf/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@download_pdf'])->name('billcode.download_pdf');

	//Manage Bill Code Items
	Route::resource('billcodeItems', 'BillcodeItemController');
	Route::POST('/billcodes_item/store',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'BillcodeItemController@store'])->name('billcodesitem.store');
    
    //AJAX Part
    Route::get('/billcodes/pi/items/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@get_item_by_pi']);
    Route::get('/ajax/pi-billcodes/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AjaxController@get_billcodes_by_pi']);
    Route::get('/ajax/billcode-item/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AjaxController@get_items_by_billcode']);


	//Manage Finish Part
	Route::resource('finishPart', 'FinishPartController');
	Route::get('/dyeing_chart',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@index']);
	Route::get('/new_dyeing_information',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@create'])->name('finishPart.add');
	Route::POST('/finish_part/store',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@store'])->name('finishPart.store');
	Route::POST('/dyeing_chart_data',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@finish_part_data'])->name('finish_part_data');

	//Manage Orders
	Route::resource('orders', 'orderController');
	Route::get('/order_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@index']);
	Route::get('/new_order',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@create']);
	Route::POST('/add_item_to_order',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@add_item_to_order']);
    Route::get('/order_pdf/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@download_pdf'])->name('order.order_details_pdf');
	Route::POST('/change_order_status',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@change_order_status']);
	
	//Manage Customer
	Route::resource('customer', 'CustomerController');
	Route::get('/customer_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'CustomerController@index']);
	Route::get('/new_customer',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'CustomerController@create']);
	//Report
    //Account report

    Route::get('/report/advance_balance',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@advance_balance'])->name('report.advance_balance');
    Route::post('/report/advance_balance',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@advance_balance_data']);
    Route::get('/report/loans',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@loans_report'])->name('report.loans');
    Route::post('/report/loans',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@loans_report_data']);


		
	//Manage Report
	Route::resource('report', 'reportController');

	// Merchandising Area
	Route::resource('merchandising', 'merchandisingController');
	Route::get('/production_report',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@production_sheet']);
	Route::get('/cost_report',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@cost_sheet']);
	Route::get('/greige_chart',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@greige_chart_view']);
	Route::POST('/greige_chart_data',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@greige_chart_data'])->name('greige_chart_data');
	Route::POST('/production_sheet',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@production_sheet_data'])->name('production_sheet_data');

	Route::get('/new_stock_fabric',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@new_stock_fabric'])->name('merchandising.stock_fabric.add');
	Route::get('/stock_fabric',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@stock_fabric']);

resources/views/loans/give_loan.blade.php
@extends('layouts.master')
@section('extra_css')

@endsection
@section('content')

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    
    @if(Session::has('message'))
      <p id="alert_message" class="alert alert-success">{{ Session::get('message') }}</p>
    @endif
    @if(Session::has('failedMessage'))
       <p id="alert_message" class="alert alert-danger">{{Session::get('failedMessage')}}</p>
    @endif

    <div class="x_panel">
      <div class="x_title">
        <h2><i class="fa fa-money"></i> Give Loan List </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".add_new"><i class="fa fa-plus-square "></i> Add New </button>
          </li>
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
         
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="datatable-responsive" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Serial</th>
              <th>Name/Others</th>
              <th>Details</th>
              <th>Loan Date</th>
              <th>Give Loan TAKA</th>
              <th>Return TAKA</th>
              <th>Balance</th>
              <th>Created By</th>
              <th>Action</th>
            </tr>
          </thead>


          <tbody>
          @php $i=0; @endphp
          @foreach($loans as $loan)
            <tr>
              <td>{{++$i}}</td>
              <td>{{$loan->name}}</td>
              <td>{{$loan->details}}</td>
              <td>{{$loan->loanDate}}</td>
              <td> @money(\Illuminate\Support\Facades\DB::table('tbgive_loan_history')->where([['loanId','=',$loan->id],['paymentType','=','1']])->sum('amount'))</td>
              <td>@money(\Illuminate\Support\Facades\DB::table('tbgive_loan_history')->where([['loanId','=',$loan->id],['paymentType','=','2']])->sum('amount'))</td>
              
              <td>@money((\Illuminate\Support\Facades\DB::table('tbgive_loan_history')->where([['loanId','=',$loan->id],['paymentType','=','1']])->sum('amount'))-(\Illuminate\Support\Facades\DB::table('tbgive_loan_history')->where([['loanId','=',$loan->id],['paymentType','=','2']])->sum('amount')))</td>

              <td>{{$loan->created_by}}</td>
              <td>

                <a href="{{route('giveLoan.show',$loan->id)}}"   title="View Loan Details" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>

                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target=".edit{{$loan->id}}"><i class="fa fa-edit"></i></button>
                
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target=".delete{{$loan->id}}"><i class="fa fa-trash"></i></button>
              </td>
            </tr>



          <div class="modal fade edit{{$loan->id}}" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">

                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel2"><b>Edit Information</b></h4>
                </div>
                <div class="modal-body">
                {!! Form::open(['method'=>'PATCH', 'action'=>['giveLoanController@update', $loan->id]]) !!}
                  

                  <div class="form-group">
                    <label for="name">Name/Others</label>
                    <input type="text" name="name" class="form-control form-white" id="name" placeholder="Loaner Name/Others" value="{{$loan->name}}" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="details">Details</label>
                    <textarea  name="details" class="form-control form-white" id="details" placeholder="Loan Details" >{{$loan->details}}</textarea>
                  </div>

                  <div class="form-group">
                    <label for="address">Address</label>
                    <textarea  name="address" class="form-control form-white" id="address" placeholder="Address" >{{$loan->address}}</textarea>
                  </div>

                  <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="text" name="phone" class="form-control form-white" id="phone" placeholder="Phone Number" value="{{$loan->phone}}" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" name="email" class="form-control form-white" id="email" placeholder="Email Address" value="{{$loan->email}}" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="loanDate">Loan Date</label>
                    <input type="date" name="loanDate" value="{{$loan->loanDate}}" class="form-control form-white" id="loanDate" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="remarks">Remarks</label>
                    <textarea  name="remarks" class="form-control form-white" id="remarks" placeholder="Remarks" >{{$loan->remarks}}</textarea>
                  </div>
                  <hr>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save changes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
                  </div>

                {{ Form::close() }}
                 
                </div>
                <div class="modal-footer">
                </div>

              </div>
            </div>
          </div>


            <div class="modal fade delete{{$loan->id}}" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">

                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel2"><b>Confirm Delete</b></h4>
                  </div>
                  <div class="modal-body">
                    {!! Form::open(['method'=>'DELETE', 'action'=>['giveLoanController@destroy', $loan->id]]) !!}
                      <button type="submit" class="btn btn-danger"><i class="fa fa-check-circle"></i> Confirm</button>
                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
                    {!! Form::close() !!}
                    
                  </div>
                  <div class="modal-footer">
                  </div>

                </div>
              </div>
            </div>


            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="modal fade add_new" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel2"><b><i class="fa fa-ils"></i> Give New Loan</b></h4>
      </div>
      <div class="modal-body">
      {!! Form::open(array('action' => 'giveLoanController@store', 'method' => 'POST')) !!}

        <div class="form-group">
          <label for="name">Name/Others</label>
          <input type="text" name="name" class="form-control form-white" id="name" placeholder="Loaner Name/Others" required >
        </div>

        <br />

        <div class="form-group">
          <label for="details">Details</label>
          <textarea  name="details" class="form-control form-white" id="details" placeholder="Loan Details" ></textarea>
        </div>


        <div class="form-group">
          <label for="phone">Phone Number</label>
          <input type="text" name="phone" class="form-control form-white" id="phone" placeholder="Phone Number" >
        </div>

        <br />

        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" name="email" class="form-control form-white" id="email" placeholder="Email Address" >
        </div>

        <br />

        <div class="form-group">
          <label for="address">Address</label>
          <textarea  name="address" class="form-control form-white" id="address" placeholder="Address" ></textarea>
        </div>

        <br />

        <div class="form-group">
          <label for="amount">Loan Amount</label>
          <input type="number" step="any" name="amount" class="form-control form-white" id="amount" required >
        </div>

        <br />

        <div class="form-group">
          <label for="loanDate">Loan Date</label>
          <input type="date" name="loanDate" class="form-control form-white" id="loanDate" required >
        </div>

        <br />

        <div class="form-group">
          <label for="remarks">Remarks</label>
          <textarea name="remarks" class="form-control form-white" id="remarks" placeholder="Remarks" ></textarea>
        </div>


        <hr>

        <div class="form-group">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save changes</button>
          <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
        </div>

        {{ Form::close() }}

      </div>
      <div class="modal-footer">
      </div>

    </div>
  </div>
</div>


@endsection
@section('extra_scripts')
  <script>
      $(document).ready(function() {

        $('#datatable-responsive').DataTable({
        	 "pageLength": 50
        });

      });
      setTimeout(function() {
            $('#alert_message').fadeOut('fast');
        }, 5000);
    </script>
@endsection

resources/views/loans/receive_loan.blade.php
@extends('layouts.master')
@section('extra_css')

@endsection
@section('content')

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    
    @if(Session::has('message'))
      <p id="alert_message" class="alert alert-success">{{ Session::get('message') }}</p>
    @endif
    @if(Session::has('failedMessage'))
       <p id="alert_message" class="alert alert-danger">{{Session::get('failedMessage')}}</p>
    @endif

    <div class="x_panel">
      <div class="x_title">
        <h2><i class="fa fa-money"></i> Receive Loan List </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".add_new"><i class="fa fa-plus-square "></i> Add New </button>
          </li>
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
         
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="datatable-responsive" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Serial</th>
              <th>Name/Others</th>
              <th>Details</th>
              <th>Loan Date</th>
              <th>Receive Loan TAKA</th>
              <th>Return TAKA</th>
              <th>Balance</th>
              <th>Created By</th>
              <th>Action</th>
            </tr>
          </thead>


          <tbody>
          @php $i=0; @endphp
          @foreach($loans as $loan)
            <tr>
              <td>{{++$i}}</td>
              <td>{{$loan->name}}</td>
              <td>{{$loan->details}}</td>
              <td>{{$loan->loanDate}}</td>
              <td> @money(\Illuminate\Support\Facades\DB::table('tbreceived_loan_history')->where([['loanId','=',$loan->id],['paymentType','=','1']])->sum('amount'))</td>
              <td>@money(\Illuminate\Support\Facades\DB::table('tbreceived_loan_history')->where([['loanId','=',$loan->id],['paymentType','=','2']])->sum('amount'))</td>
              
              <td>@money((\Illuminate\Support\Facades\DB::table('tbreceived_loan_history')->where([['loanId','=',$loan->id],['paymentType','=','1']])->sum('amount'))-(\Illuminate\Support\Facades\DB::table('tbreceived_loan_history')->where([['loanId','=',$loan->id],['paymentType','=','2']])->sum('amount')))</td>

              <td>{{$loan->created_by}}</td>
              <td>

                <a href="{{route('receiveLoan.show',$loan->id)}}"   title="View Loan Details" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>

                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target=".edit{{$loan->id}}"><i class="fa fa-edit"></i></button>
                
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target=".delete{{$loan->id}}"><i class="fa fa-trash"></i></button>
              </td>
            </tr>



          <div class="modal fade edit{{$loan->id}}" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">

                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel2"><b>Edit Receive Loan Information</b></h4>
                </div>
                <div class="modal-body">
                {!! Form::open(['method'=>'PATCH', 'action'=>['receiveLoanController@update', $loan->id]]) !!}
                  

                  <div class="form-group">
                    <label for="name">Name/Others</label>
                    <input type="text" name="name" class="form-control form-white" id="name" placeholder="Loaner Name/Others" value="{{$loan->name}}" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="details">Details</label>
                    <textarea  name="details" class="form-control form-white" id="details" placeholder="Loan Details" >{{$loan->details}}</textarea>
                  </div>

                  <div class="form-group">
                    <label for="address">Address</label>
                    <textarea  name="address" class="form-control form-white" id="address" placeholder="Address" >{{$loan->address}}</textarea>
                  </div>

                  <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="text" name="phone" class="form-control form-white" id="phone" placeholder="Phone Number" value="{{$loan->phone}}" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" name="email" class="form-control form-white" id="email" placeholder="Email Address" value="{{$loan->email}}" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="loanDate">Loan Date</label>
                    <input type="date" name="loanDate" value="{{$loan->loanDate}}" class="form-control form-white" id="loanDate" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="remarks">Remarks</label>
                    <textarea  name="remarks" class="form-control form-white" id="remarks" placeholder="Remarks" >{{$loan->remarks}}</textarea>
                  </div>
                  <hr>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save changes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
                  </div>

                {{ Form::close() }}
                 
                </div>
                <div class="modal-footer">
                </div>

              </div>
            </div>
          </div>


            <div class="modal fade delete{{$loan->id}}" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">

                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel2"><b>Confirm Delete</b></h4>
                  </div>
                  <div class="modal-body">
                    {!! Form::open(['method'=>'DELETE', 'action'=>['receiveLoanController@destroy', $loan->id]]) !!}
                      <button type="submit" class="btn btn-danger"><i class="fa fa-check-circle"></i> Confirm</button>
                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
                    {!! Form::close() !!}
                    
                  </div>
                  <div class="modal-footer">
                  </div>

                </div>
              </div>
            </div>


            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="modal fade add_new" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel2"><b><i class="fa fa-ils"></i> Receive New Loan</b></h4>
      </div>
      <div class="modal-body">
      {!! Form::open(array('action' => 'receiveLoanController@store', 'method' => 'POST')) !!}

        <div class="form-group">
          <label for="name">Name/Others</label>
          <input type="text" name="name" class="form-control form-white" id="name" placeholder="Loaner Name/Others" required >
        </div>

        <br />

        <div class="form-group">
          <label for="details">Details</label>
          <textarea  name="details" class="form-control form-white" id="details" placeholder="Loan Details" ></textarea>
        </div>


        <div class="form-group">
          <label for="phone">Phone Number</label>
          <input type="text" name="phone" class="form-control form-white" id="phone" placeholder="Phone Number" >
        </div>

        <br />

        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" name="email" class="form-control form-white" id="email" placeholder="Email Address" >
        </div>

        <br />

        <div class="form-group">
          <label for="address">Address</label>
          <textarea  name="address" class="form-control form-white" id="address" placeholder="Address" ></textarea>
        </div>

        <br />

        <div class="form-group">
          <label for="amount">Loan Amount</label>
          <input type="number" placeholder="Amount" step="any" name="amount" class="form-control form-white" id="amount" required >
        </div>

        <br />

        <div class="form-group">
          <label for="loanDate">Loan Date</label>
          <input type="date" name="loanDate" class="form-control form-white" id="loanDate" required >
        </div>

        <br />

        <div class="form-group">
          <label for="remarks">Remarks</label>
          <textarea name="remarks" class="form-control form-white" id="remarks" placeholder="Remarks" ></textarea>
        </div>


        <hr>

        <div class="form-group">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save changes</button>
          <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
        </div>

        {{ Form::close() }}

      </div>
      <div class="modal-footer">
      </div>

    </div>
  </div>
</div>


@endsection
@section('extra_scripts')
  <script>
      $(document).ready(function() {

        $('#datatable-responsive').DataTable({
        	 "pageLength": 50
        });

      });
      setTimeout(function() {
            $('#alert_message').fadeOut('fast');
        }, 5000);
    </script>
@endsection