routes/web.php
	Route::POST('/transaction_history_data',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@transaction_history_data'])->name('transaction_history_data');

	//Manage Expenses
	Route::resource('expenses', 'ExpensesController');
	Route::get('/expenses',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@index']);
	Route::get('/todays_expense_history',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@todays_expenses']);
	Route::get('/new_expense',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@create']);

	//Manage Expense Category
	Route::resource('expenseCategory', 'ExpenseCategoryController');
	Route::get('/expense_category',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpenseCategoryController@index']);

	//Manage Income Category
	Route::resource('incomeSourceCategory', 'IncomeSourceCategoryController');
	Route::get('/incomes_category',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceCategoryController@index']);


	//Manage Expenses
	Route::resource('incomes', 'IncomeSourceController');
	Route::get('/incomes_delete/{income}',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@show_delete'])->name('incomes.delete');
	Route::get('/incomes',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@index']);
	Route::get('/todays_income_history',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@todays_income']);
	Route::get('/new_incomes',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@create']);

	//Manage Give Loan
	Route::resource('giveLoan', 'giveLoanController');
	Route::get('/give_loan',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@index']);
	Route::POST('/give_new_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@giveNewLoan']);
	Route::POST('/give_return_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@giveReturnLoan']);

	//Manage Receive Loan
	Route::resource('receiveLoan', 'receiveLoanController');
	Route::get('/receive_loan',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@index']);
	Route::POST('/receive_new_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@giveNewLoan']);
	Route::POST('/receive_return_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@giveReturnLoan']);

	//Manage Advance Payment
	Route::resource('advancePayment', 'advancePaymentController');
	Route::get('/manage_advance_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@index']);
	Route::POST('/advance_new_expense',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@advanceNewExpense']);
	Route::POST('/give_new_advance_amount',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@advanceNewPayment']);

	//Manage Bill Code
	Route::resource('billcodes', 'billcodeController');
	Route::get('/generate_bill_code',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@create']);
	Route::get('/bill_code_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@index']);
    Route::get('/barcode_pdf/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@download_pdf'])->name('billcode.download_pdf');

	//Manage Bill Code Items
	Route::resource('billcodeItems', 'BillcodeItemController');
	Route::POST('/billcodes_item/store',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'BillcodeItemController@store'])->name('billcodesitem.store');
    
    //AJAX Part
    Route::get('/billcodes/pi/items/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@get_item_by_pi']);
    Route::get('/ajax/pi-billcodes/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AjaxController@get_billcodes_by_pi']);
    Route::get('/ajax/billcode-item/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AjaxController@get_items_by_billcode']);


	//Manage Finish Part
	Route::resource('finishPart', 'FinishPartController');
	Route::get('/dyeing_chart',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@index']);
	Route::get('/new_dyeing_information',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@create'])->name('finishPart.add');
	Route::POST('/finish_part/store',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@store'])->name('finishPart.store');
	Route::POST('/dyeing_chart_data',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@finish_part_data'])->name('finish_part_data');

	//Manage Orders
	Route::resource('orders', 'orderController');
	Route::get('/order_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@index']);
	Route::get('/new_order',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@create']);
	Route::POST('/add_item_to_order',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@add_item_to_order']);
    Route::get('/order_pdf/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@download_pdf'])->name('order.order_details_pdf');
	Route::POST('/change_order_status',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@change_order_status']);
	
	//Manage Customer
	Route::resource('customer', 'CustomerController');
	Route::get('/customer_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'CustomerController@index']);
	Route::get('/new_customer',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'CustomerController@create']);
	//Report
    //Account report

    Route::get('/report/advance_balance',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@advance_balance'])->name('report.advance_balance');
    Route::post('/report/advance_balance',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@advance_balance_data']);
    Route::get('/report/loans',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@loans_report'])->name('report.loans');
    Route::post('/report/loans',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@loans_report_data']);


		
	//Manage Report
	Route::resource('report', 'reportController');

	// Merchandising Area
	Route::resource('merchandising', 'merchandisingController');
	Route::get('/production_report',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@production_sheet']);
	Route::get('/cost_report',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@cost_sheet']);
	Route::get('/greige_chart',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@greige_chart_view']);
	Route::POST('/greige_chart_data',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@greige_chart_data'])->name('greige_chart_data');
	Route::POST('/production_sheet',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@production_sheet_data'])->name('production_sheet_data');

	Route::get('/new_stock_fabric',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@new_stock_fabric'])->name('merchandising.stock_fabric.add');
	Route::get('/stock_fabric',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@stock_fabric']);
	Route::POST('/stock_fabric_store',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@stock_fabric_store'])->name('stock_fabric_store');
	Route::POST('/stock_fabric',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@stock_fabric_data'])->name('stock_fabric_data');


	//Commercial Management Area 
	Route::resource('commercialTask', 'CommercialController');
	Route::get('/new_lc',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@create'])->name('lc.new_lc');
	Route::get('/lc_list',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@lc_list_view'])->name('lc.list');
	Route::POST('/lc_data',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@lc_list_data'])->name('lc.lc_list_data');
    Route::get('/lc_details/{id}',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@show'])->name('lc.show');
    Route::get('/negotiation_application/{id}',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@negotiation_application_pdf'])->name('commercial.negotiation_application_pdf');
    Route::get('/bill_of_exchange/{id}',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@bill_of_exchange_pdf'])->name('commercial.bill_of_exchange_pdf');

app/Http/Controllers/billcodeController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use PDF;

class billcodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $billcodes=DB::table('tbbillcode')
        ->leftJoin('users','users.id','=','tbbillcode.createdBy')
        ->select('tbbillcode.*','users.name as created_by')
        ->get();
        return view('billcodes.index',compact('billcodes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $billcodeData=DB::table('tbbillcode')->latest()->first();
        if($billcodeData){
            $billcode = ($billcodeData->billcode)+1;
        }else{
            $billcode = 101;
        }
        return view('billcodes.create',compact('billcode'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $this->validate($request,[
            'billcode'=>'required',
            'bDate'=>'required'
        ]);

        $now=Carbon::now()->toDateTimeString();
        $user=Auth::user();
        $str=DB::table('tbbillcode')->insert([
            'billcode'=>$request->billcode,
            'bDate'=>Carbon::parse($request->bDate)->format('Y-m-d'),
            'remarks'=>$request->remarks,
            'createdBy'=>$user->id,
            'created_at'=>$now,
            'updated_at'=>$now,

        ]);

        if($str)
        {
            Session::flash('message','Billcode '.$request->billcode.' Successfully Generated. ');
        }else{
            Session::flash('failedMessage','Billcode Generation Failed.');
        }
        return redirect('/bill_code_list');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
//        return $id;
        $billcodeitems=DB::table('tbbillcodeitems')
        ->leftJoin('users','users.id','=','tbbillcodeitems.createdBy')
        ->leftJoin('tborders','tborders.id','=','tbbillcodeitems.bcPi_number')
        ->leftJoin('tborders_details','tborders_details.id','=','tbbillcodeitems.bcOritem_id')
        ->select('tbbillcodeitems.*','tborders.pi','tborders_details.details','tborders_details.color','tborders_details.orderQuantity as bookingQuantity','users.name as created_by')
        ->where('tbbillcodeitems.billcodeId','=',base64_decode($id))
        ->get();

        $billcodeDetails=DB::table('tbbillcode')
        ->where('tbbillcode.id','=',base64_decode($id))
        ->first();
        
        $orderId=DB::table('tborders')
        ->select('tborders.id','tborders.pi')
        ->where('status','=','0')
        ->get();

        $billcodeId=$id;
        return view('billcodes.details',compact('orderId','billcodeId','billcodeitems','billcodeDetails'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'billcode'=>'required',
            'bDate'=>'required'
        ]);

        $now=Carbon::now()->toDateTimeString();
        $user=Auth::user();
        $str=DB::table('tbbillcode')->where(['id'=>$id])->update([
            'billcode'=>$request->billcode,
            'bDate'=>Carbon::parse($request->bDate)->format('Y-m-d'),
            'remarks'=>$request->remarks,
            'createdBy'=>$user->id,
            'updated_at'=>$now,

        ]);

        if($str)
        {
            Session::flash('message','Billcode '.$request->billcode.' Has Been Successfully Updated. ');
        }else{
            Session::flash('failedMessage','Billcode Updation Failed.');
        }
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function download_pdf($id)
    {
        
        $billcodeitems=DB::table('tbbillcodeitems')
        ->leftJoin('users','users.id','=','tbbillcodeitems.createdBy')
        ->leftJoin('tborders','tborders.id','=','tbbillcodeitems.bcPi_number')
        ->leftJoin('tborders_details','tborders_details.id','=','tbbillcodeitems.bcOritem_id')
        ->select('tbbillcodeitems.*','tborders.pi','tborders_details.details','tborders_details.color','tborders_details.orderQuantity as bookingQuantity','users.name as created_by')
        ->where('tbbillcodeitems.billcodeId','=',$id)
        ->get();

        $billcodeDetails=DB::table('tbbillcode')
        ->where('tbbillcode.id','=',$id)
        ->first();

        $totbcQuantity=0;
        $tunit=0;
        foreach($billcodeitems as $item){
            $totbcQuantity+=$item->bcQuantity;
            $tunit+=$item->bcUnitPrice;
        }
        $tunit=$tunit/$billcodeitems->count();
        $billcodeitems->totbcQuantity=$totbcQuantity;
        $billcodeitems->tunit=$tunit;
        $orderId=DB::table('tborders')
        ->select('tborders.id','tborders.pi')
        ->get();

        $billcodeId=$id;
        // dd($billcodeitems->tunit);
        // return view('billcodes.download_pdf',compact('orderId','billcodeId','billcodeitems','billcodeDetails'));
        $pdf=PDF::loadView('billcodes.download_pdf',compact('orderId','billcodeId','billcodeitems','billcodeDetails'));
        $filename=time()."_billcode.pdf";
        return $pdf->download($filename);
        
    }


}

resources/views/billcodes/create.blade.php
@extends('layouts.master')
@section('content')

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">

    <div class="x_panel">
      <div class="x_title">
        <h2><i class="fa fa-money"></i> Generate New Bill Code </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">

        {!! Form::open(['method'=>'POST','action'=>'billcodeController@store']) !!}
      
        <div class="form-group">
          <label for="billcode">Bill Code</label>
          <input type="text" readonly value="{{$billcode}}" name="billcode" class="form-control form-white" id="billcode" placeholder="Bill Code Number " required >
        </div>

        <br />

        <div class="form-group">
          <label for="bDate">Bill Code Date</label>
          <input name="bDate" value="{{date('Y-m-d')}}" type="text" class="form-control form-white" id="bDate" required />
        </div>

        <br />
        
        <div class="form-group">
          <label for="remarks">Remarks</label>
          <textarea name="remarks" class="form-control form-white" id="remarks" placeholder="Remarks" ></textarea>
        </div>

        <hr>

        <div class="form-group">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Billcode</button>
          <button type="reset" class="btn btn-default"><i class="fa fa-refresh"></i> Reset</button>
        </div>

        {{ Form::close() }}


      </div>
    </div>
  </div>

</div>
@endsection
@section('extra_scripts')
<script>
  setTimeout(function() {
    $('#alert_message').fadeOut('fast');
  }, 5000);
</script>
@endsection

resources/views/billcodes/download_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Billcode</title>
</head>
<body>
	<style type="text/css">
		@page { sheet-size: A4-L; }
		.table2{
			border-collapse: collapse;
			width: 100%;
			text-align: center;
		}
		.table2 td,th{
			border:1px solid black;
			font-size: 12px;
		}
		.table2 td{
			padding: 7px 2px;
		}
		.table2 th{
			padding: 3px 1px;
		}
		.table3{
			border-collapse: collapse;
			text-align: center;
			width: 100%;
			text-decoration: underline;
			font-weight: bold;
			font-size: 12px;
			padding-bottom:30px; 
		}
		.table3 td{
			text-decoration: underline;
		}
	</style>
	<table border="1px" class="table2">
		<tr>
			<th rowspan="2">BUY GREIGE</th>
			<th>Yds</th>
			<th>Unit Price</th>
			<th>Total</th>
			<th colspan="4" rowspan="2">PURCHESS</th>
			<th colspan="2">Date: {{$billcodeDetails->bDate}}</th>
		</tr>
		<tr>
			<td>{{$billcodeitems->totbcQuantity}}</td>
			<td>{{$billcodeitems->tunit}}</td>
			<td>{{($billcodeitems->totbcQuantity)*($billcodeitems->tunit)}}</td>
			<th colspan="2">BILL Code: {{$billcodeDetails->billcode}}</th>
		</tr>
		<tr>
			<th>Description Of <br /> The Goods</th>
			<th width="12%">PI</th>
			<th width="10%">Color</th>
			<th width="8%">Booking QTY</th>
			<th width="7%">QTY</th>
			<th width="7%">Unit Price (TK)</th>
			<th width="8%">Total Amount (TK)</th>
			<th width="10%">From</th>
			<th width="10%">To</th>
			<th width="10%">Remarks</th>
		</tr>
		<tbody>
	    @php $i=0;$qty=0;$total=0; @endphp
	     @forelse($billcodeitems as $bci)
	      @php $qty+=($bci->bcQuantity);$total+=($bci->bcQuantity)*($bci->bcUnitPrice); @endphp
	      <tr>
	        <td>{{$bci->details}}</td>
	        <td>{{$bci->pi}}</td>
	        <td>{{$bci->color}}</td>
	        <td>{{$bci->bookingQuantity}}</td>
	        <td>{{$bci->bcQuantity}}</td>
	        <td>{{$bci->bcUnitPrice}}</td>
	        <td>{{($bci->bcQuantity)*($bci->bcUnitPrice)}}</td>
	        <td>{{($bci->bcFrom)}}</td>
	        <td>{{($bci->bcTo)}}</td>
	        <td>{{($bci->bcRemarks)}}</td>
	      </tr>
	     @empty
	      <tr>
	        <td colspan="10"> No data found.</td>
	      </tr>
	      @endforelse
	    </tbody>
	</table>
	<div style="font-size:13px;font-weight:bold;padding:30px 25px;">NOTES:</div>
	<table class="table3" style="margin-bottom:50px;">
		<tr>
			<td width="25%">Merchandiser</td>
			<td width="25%">Accounts</td>
			<td width="25%">GM</td>
			<td width="25%">MD</td>
		</tr>
	</table>
	<div style="font-size:13px;font-weight:bold;padding:25px 25px;text-decoration:underline;">Comments:</div>

</body>
</html>

resources/views/billcodes/index.blade.php
@extends('layouts.master')
@section('extra_css')

@endsection
@section('content')

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    
    @if(Session::has('message'))
      <p id="alert_message" class="alert alert-success">{{ Session::get('message') }}</p>
    @endif
    @if(Session::has('failedMessage'))
       <p id="alert_message" class="alert alert-danger">{{Session::get('failedMessage')}}</p>
    @endif

    <div class="x_panel">
      <div class="x_title">
        <h2><i class="fa fa-th"></i> Billcode List </h2>
        <ul class="nav navbar-right panel_toolbox">
          <!-- <li><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".add_new"><i class="fa fa-plus-square "></i> Add New </button></li> -->
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
         
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="datatable-responsive" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th width="5%">Serial</th>
              <th>Bill Code</th>
              <th>Date</th>
              <th>Remarks</th>
              <th>Created By</th>
              <th width="15%">Action</th>
            </tr>
          </thead>


          <tbody>
          @php $i=0; @endphp
          @foreach($billcodes as $billcode)
            <tr>
              <td>{{++$i}}</td>
              <td>{{$billcode->billcode}}</td>
              <td>{{$billcode->bDate}}</td>
              <td>{{$billcode->remarks}}</td>
              <td>{{$billcode->created_by}}</td>
              <td>

                <a href="{{route('billcodes.show',base64_encode($billcode->id))}}"   title="View Billcode Details" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>

                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target=".edit{{$billcode->id}}"><i class="fa fa-edit"></i></button>
                
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target=".delete{{$billcode->id}}"><i class="fa fa-trash"></i></button>
              </td>
            </tr>



          <div class="modal fade edit{{$billcode->id}}" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">

                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel2"><b>Edit Information</b></h4>
                </div>
                <div class="modal-body">
                {!! Form::open(['method'=>'PATCH', 'action'=>['billcodeController@update', $billcode->id]]) !!}
                  

                  <div class="form-group">
                    <label for="billcode">Billcode</label>
                    <input type="text" name="billcode" class="form-control form-white" id="billcode" placeholder="Billcode" value="{{$billcode->billcode}}" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="bDate">Date</label>
                    <input type="date" name="bDate" value="{{$billcode->bDate}}" class="form-control form-white" id="bDate" required >
                  </div>

                  <br />

                  <div class="form-group">
                    <label for="remarks">Remarks</label>
                    <textarea  name="remarks" class="form-control form-white" id="remarks" placeholder="Remarks" >{{$billcode->remarks}}</textarea>
                  </div>
                  <hr>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save changes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
                  </div>

                {{ Form::close() }}
                 
                </div>
                <div class="modal-footer">
                </div>

              </div>
            </div>
          </div>


            <div class="modal fade delete{{$billcode->id}}" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">

                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel2"><b>Confirm Delete</b></h4>
                  </div>
                  <div class="modal-body">
                    {!! Form::open(['method'=>'DELETE', 'action'=>['billcodeController@destroy', $billcode->id]]) !!}
                      <button type="submit" class="btn btn-danger"><i class="fa fa-check-circle"></i> Confirm</button>
                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
                    {!! Form::close() !!}
                    
                  </div>
                  <div class="modal-footer">
                  </div>

                </div>
              </div>
            </div>


            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="modal fade add_new" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel2"><b><i class="fa fa-ils"></i> Generate New Billcode</b></h4>
      </div>
      <div class="modal-body">
      {!! Form::open(array('action' => 'billcodeController@store', 'method' => 'POST')) !!}

        <div class="form-group">
          <label for="billcode">Bill Code</label>
          <input type="text" name="billcode" class="form-control form-white" id="billcode" placeholder="Billcode" required >
        </div>

        <br />

        <div class="form-group">
          <label for="loanDate">Date</label>
          <input type="date" name="bDate" class="form-control form-white" id="bDate" required >
        </div>

        <br />

        <div class="form-group">
          <label for="remarks">Remarks</label>
          <textarea name="remarks" class="form-control form-white" id="remarks" placeholder="Remarks" ></textarea>
        </div>

        <hr>

        <div class="form-group">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save changes</button>
          <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
        </div>

        {{ Form::close() }}

      </div>
      <div class="modal-footer">
      </div>

    </div>
  </div>
</div>


@endsection
@section('extra_scripts')
  <script>
      $(document).ready(function() {

        $('#datatable-responsive').DataTable({
        	 "pageLength": 50
        });

      });
      setTimeout(function() {
            $('#alert_message').fadeOut('fast');
        }, 5000);
    </script>
@endsection

resources/views/billcodes/item_by_pi.blade.php
<select name="oritem_id" class="form-control" required >
	<option value="">Select</option>
	@foreach($item_by_pi as $item)
		<option value="{{$item->id}}">{{$item->color}} ({{$item->style}})</option>
	@endforeach
</select>