routes/web.php
	// Cash out (Withdrow Money)
    Route::get('/cash_out',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@cash_out'])->name('cash_out');
	Route::POST('/cash_out_store',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@cash_out_store'])->name('bank.cash_out_store');

	Route::get('/transaction_history',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@transaction_history']);
	Route::POST('/transaction_history_data',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'BankController@transaction_history_data'])->name('transaction_history_data');

	//Manage Expenses
	Route::resource('expenses', 'ExpensesController');
	Route::get('/expenses',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@index']);
	Route::get('/todays_expense_history',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@todays_expenses']);
	Route::get('/new_expense',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpensesController@create']);

	//Manage Expense Category
	Route::resource('expenseCategory', 'ExpenseCategoryController');
	Route::get('/expense_category',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'ExpenseCategoryController@index']);

	//Manage Income Category
	Route::resource('incomeSourceCategory', 'IncomeSourceCategoryController');
	Route::get('/incomes_category',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceCategoryController@index']);


	//Manage Expenses
	Route::resource('incomes', 'IncomeSourceController');
	Route::get('/incomes_delete/{income}',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@show_delete'])->name('incomes.delete');
	Route::get('/incomes',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@index']);
	Route::get('/todays_income_history',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@todays_income']);
	Route::get('/new_incomes',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'IncomeSourceController@create']);

	//Manage Give Loan
	Route::resource('giveLoan', 'giveLoanController');
	Route::get('/give_loan',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@index']);
	Route::POST('/give_new_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@giveNewLoan']);
	Route::POST('/give_return_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'giveLoanController@giveReturnLoan']);

	//Manage Receive Loan
	Route::resource('receiveLoan', 'receiveLoanController');
	Route::get('/receive_loan',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@index']);
	Route::POST('/receive_new_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@giveNewLoan']);
	Route::POST('/receive_return_loan_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'receiveLoanController@giveReturnLoan']);

	//Manage Advance Payment
	Route::resource('advancePayment', 'advancePaymentController');
	Route::get('/manage_advance_payment',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@index']);
	Route::POST('/advance_new_expense',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@advanceNewExpense']);
	Route::POST('/give_new_advance_amount',['middleware'=>'check-permission:admin|superadmin|accountant','uses'=>'advancePaymentController@advanceNewPayment']);

	//Manage Bill Code
	Route::resource('billcodes', 'billcodeController');
	Route::get('/generate_bill_code',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@create']);
	Route::get('/bill_code_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@index']);
    Route::get('/barcode_pdf/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'billcodeController@download_pdf'])->name('billcode.download_pdf');

	//Manage Bill Code Items
	Route::resource('billcodeItems', 'BillcodeItemController');
	Route::POST('/billcodes_item/store',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'BillcodeItemController@store'])->name('billcodesitem.store');
    
    //AJAX Part
    Route::get('/billcodes/pi/items/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@get_item_by_pi']);
    Route::get('/ajax/pi-billcodes/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AjaxController@get_billcodes_by_pi']);
    Route::get('/ajax/billcode-item/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AjaxController@get_items_by_billcode']);


	//Manage Finish Part
	Route::resource('finishPart', 'FinishPartController');
	Route::get('/dyeing_chart',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@index']);
	Route::get('/new_dyeing_information',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@create'])->name('finishPart.add');
	Route::POST('/finish_part/store',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@store'])->name('finishPart.store');
	Route::POST('/dyeing_chart_data',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'FinishPartController@finish_part_data'])->name('finish_part_data');

	//Manage Orders
	Route::resource('orders', 'orderController');
	Route::get('/order_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@index']);
	Route::get('/new_order',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@create']);
	Route::POST('/add_item_to_order',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@add_item_to_order']);
    Route::get('/order_pdf/{id}',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@download_pdf'])->name('order.order_details_pdf');
	Route::POST('/change_order_status',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'orderController@change_order_status']);
	
	//Manage Customer
	Route::resource('customer', 'CustomerController');
	Route::get('/customer_list',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'CustomerController@index']);
	Route::get('/new_customer',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'CustomerController@create']);
	//Report
    //Account report

    Route::get('/report/advance_balance',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@advance_balance'])->name('report.advance_balance');
    Route::post('/report/advance_balance',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@advance_balance_data']);
    Route::get('/report/loans',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@loans_report'])->name('report.loans');
    Route::post('/report/loans',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'AccountReportController@loans_report_data']);


		
	//Manage Report
	Route::resource('report', 'reportController');

	// Merchandising Area
	Route::resource('merchandising', 'merchandisingController');
	Route::get('/production_report',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@production_sheet']);
	Route::get('/cost_report',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@cost_sheet']);
	Route::get('/greige_chart',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@greige_chart_view']);
	Route::POST('/greige_chart_data',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@greige_chart_data'])->name('greige_chart_data');
	Route::POST('/production_sheet',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@production_sheet_data'])->name('production_sheet_data');

	Route::get('/new_stock_fabric',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@new_stock_fabric'])->name('merchandising.stock_fabric.add');
	Route::get('/stock_fabric',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@stock_fabric']);
	Route::POST('/stock_fabric_store',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@stock_fabric_store'])->name('stock_fabric_store');
	Route::POST('/stock_fabric',['middleware'=>'check-permission:admin|superadmin|merchandiser','uses'=>'merchandisingController@stock_fabric_data'])->name('stock_fabric_data');


	//Commercial Management Area 
	Route::resource('commercialTask', 'CommercialController');
	Route::get('/new_lc',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@create'])->name('lc.new_lc');
	Route::get('/lc_list',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@lc_list_view'])->name('lc.list');
	Route::POST('/lc_data',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@lc_list_data'])->name('lc.lc_list_data');
    Route::get('/lc_details/{id}',['middleware'=>'check-permission:admin|superadmin|commercial','uses'=>'CommercialController@show'])->name('lc.show');

app/Http/Controllers/advancePaymentController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class advancePaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees=DB::table('users')->get();
        $advance_payment=DB::table('tbadvance_payment')
        ->leftJoin('users as createBy','createBy.id','=','tbadvance_payment.createdBy')
        ->leftJoin('users as employeeInfo','employeeInfo.id','=','tbadvance_payment.empId')
        ->select('tbadvance_payment.*','createBy.name as created_by','employeeInfo.name as employeeName')
        ->get();
        return view('advance_payment.index',compact('advance_payment','employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      
        $this->validate($request,[
            'employeeId'=>'required',
            'advanceDate'=>'required',
            'advanceAmount'=>'required'
        ]);
        $now=Carbon::now()->toDateTimeString();
        $user=Auth::user();
        $str=DB::table('tbadvance_payment')->insertGetId([
            'empId'=>$request->employeeId,
            'remarks'=>$request->remarks,
            'paymentDate'=>Carbon::parse($request->advanceDate)->format('Y-m-d'),
            'createdBy'=>$user->id,
            'created_at'=>$now,
            'updated_at'=>$now,

        ]);

        $str=DB::table('tbadvance_payment_history')->insert([
            'advancePaymentId'=>$str,
            'paymentType'=>'1',
            'amount'=>$request->advanceAmount,
            'aphDate'=>Carbon::parse($request->advanceDate)->format('Y-m-d'),
            'remarks'=>NULL,
            'createdBy'=>$user->id,
            'created_at'=>$now,
            'updated_at'=>$now,

        ]);
        if($str)
        {
            Session::flash('message','Advance Payment Information Successfully Inserted ');
        }else{
            Session::flash('failedMessage','Advance Payment Information Insertion Failed.');
        }
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paymentAmount = DB::table('tbadvance_payment_history')->where([['advancePaymentId','=',$id],['paymentType','=','1']])->sum('amount');
        $paymentReturnAmount = DB::table('tbadvance_payment_history')->where([['advancePaymentId','=',$id],['paymentType','=','2']])->sum('amount');
        $loanAmounts=DB::table('tbadvance_payment_history')
        ->where([['tbadvance_payment_history.advancePaymentId','=',$id],['tbadvance_payment_history.paymentType','=',1]])
        ->leftJoin('users','users.id','=','tbadvance_payment_history.createdBy')
        ->select('tbadvance_payment_history.*','users.name as created_by')
        ->get();

        $loanReturnAmounts=DB::table('tbadvance_payment_history')
        ->where([['tbadvance_payment_history.advancePaymentId','=',$id],['tbadvance_payment_history.paymentType','=',2]])
        ->leftJoin('users','users.id','=','tbadvance_payment_history.createdBy')
        ->select('tbadvance_payment_history.*','users.name as created_by')
        ->get();

        
        $advance_payments=DB::table('tbadvance_payment')
        ->leftJoin('users as createBy','createBy.id','=','tbadvance_payment.createdBy')
        ->leftJoin('users as employeeInfo','employeeInfo.id','=','tbadvance_payment.empId')
        ->select('tbadvance_payment.*','createBy.name as created_by','employeeInfo.name as employeeName','employeeInfo.email as email','employeeInfo.phone as phone','employeeInfo.currentAddress as currentAddress')
        ->get();

        $advancePaymentId = $id;

        return view('advance_payment.advance_payment_details',compact('advance_payments','loanAmounts','loanReturnAmounts','paymentAmount','paymentReturnAmount','advancePaymentId'));
 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function advanceNewExpense(Request $request)
    {
      
        $now=Carbon::now()->toDateTimeString();
        $user=Auth::user();
        $str=DB::table('tbadvance_payment_history')->insert([
            'advancePaymentId'=>$request->advancePaymentId,
            'expenseTitle'=>$request->expenseTitle,
            'categoryName'=>$request->categoryName,
            'paymentType'=>'2',
            'amount'=>$request->amount,
            'aphDate'=>Carbon::parse($request->aphDate)->format('Y-m-d'),
            'remarks'=>$request->remarks,
            'createdBy'=>$user->id,
            'created_at'=>$now,
            'updated_at'=>$now,

        ]);

        if($str)
        {
            Session::flash('message','Expense Information Successfully Inserted ');
        }else{
            Session::flash('failedMessage','Expense Information Insertion Failed.');
        }
        return redirect()->back();
    }

    public function advanceNewPayment(Request $request)
    {
      
        $now=Carbon::now()->toDateTimeString();
        $user=Auth::user();
        $str=DB::table('tbadvance_payment_history')->insert([
            'advancePaymentId'=>$request->advancePaymentId,
            'paymentType'=>'1',
            'amount'=>$request->amount,
            'aphDate'=>Carbon::parse($request->aphDate)->format('Y-m-d'),
            'remarks'=>$request->remarks,
            'createdBy'=>$user->id,
            'created_at'=>$now,
            'updated_at'=>$now,

        ]);

        if($str)
        {
            Session::flash('message','New Payment Information Successfully Inserted ');
        }else{
            Session::flash('failedMessage','New Payment Information Insertion Failed.');
        }
        return redirect()->back();
    }
}

resources/views/advance_payment/index.blade.php
@extends('layouts.master')
@section('extra_css')

@endsection
@section('content')

<div class="clearfix"></div>

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    
    @if(Session::has('message'))
      <p id="alert_message" class="alert alert-success">{{ Session::get('message') }}</p>
    @endif
    @if(Session::has('failedMessage'))
       <p id="alert_message" class="alert alert-danger">{{Session::get('failedMessage')}}</p>
    @endif

    <div class="x_panel">
      <div class="x_title">
        <h2><i class="fa fa-money"></i> Advance Payment List </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".add_new"><i class="fa fa-plus-square "></i> Add New </button>
          </li>
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
         
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="datatable-responsive" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Serial</th>
              <th>Name/Others</th>
              <th>Remarks</th>
              <th>Payment Date</th>
              <th>Advance Amount</th>
              <th>Expense Amount</th>
              <th>Balance Amount</th>
              <th>Created By</th>
              <th>Action</th>
            </tr>
          </thead>


          <tbody>
          @php $i=0; @endphp
          @foreach($advance_payment as $data)
            <tr>
              <td>{{++$i}}</td>
              <td>{{$data->employeeName}}</td>
              <td>{{$data->remarks}}</td>
              <td>{{$data->paymentDate}}</td>
              <td> @money(\Illuminate\Support\Facades\DB::table('tbadvance_payment_history')->where([['advancePaymentId','=',$data->id],['paymentType','=','1']])->sum('amount'))</td>
              <td>@money(\Illuminate\Support\Facades\DB::table('tbadvance_payment_history')->where([['advancePaymentId','=',$data->id],['paymentType','=','2']])->sum('amount'))</td>
              
              <td>@money((\Illuminate\Support\Facades\DB::table('tbadvance_payment_history')->where([['advancePaymentId','=',$data->id],['paymentType','=','1']])->sum('amount'))-(\Illuminate\Support\Facades\DB::table('tbadvance_payment_history')->where([['advancePaymentId','=',$data->id],['paymentType','=','2']])->sum('amount')))</td>

              <td>{{$data->created_by}}</td>
              <td>
                <a href="{{route('advancePayment.show',$data->id)}}"   title="View Details" class="btn btn-default btn-sm"><i class="fa fa-eye"></i></a>

                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target=".delete{{$data->id}}"><i class="fa fa-trash"></i></button>

              </td>
            </tr>


            <div class="modal fade delete{{$data->id}}" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">

                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel2"><b>Confirm Delete</b></h4>
                  </div>
                  <div class="modal-body">
                    {!! Form::open(['method'=>'DELETE', 'action'=>['advancePaymentController@destroy', $data->id]]) !!}
                      <button type="submit" class="btn btn-danger"><i class="fa fa-check-circle"></i> Confirm</button>
                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
                    {!! Form::close() !!}
                    
                  </div>
                  <div class="modal-footer">
                  </div>

                </div>
              </div>
            </div>


            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="modal fade add_new" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel2"><b><i class="fa fa-ils"></i> Give New Advance Payment</b></h4>
      </div>
      <div class="modal-body">
      {!! Form::open(array('action' => 'advancePaymentController@store', 'method' => 'POST')) !!}

        <div class="form-group">
          <label for="employeeId">Employee</label>
          <select name="employeeId" id="employeeId" required class="form-control" >
            <option selected value="">Select Employee</option>
            @foreach($employees as $employee)
              <option value="{{$employee->id}}">{{$employee->name}}</option>
            @endforeach
          </select>
        </div>

        <br />

        <div class="form-group">
          <label for="remarks">Remarks</label>
          <textarea  name="remarks" class="form-control form-white" id="remarks" placeholder="Remarks " ></textarea>
        </div>


        <div class="form-group">
          <label for="advanceDate">Advance Date</label>
          <input type="date" name="advanceDate" class="form-control form-white" id="advanceDate" required >
        </div>

        <br />

        <div class="form-group">
          <label for="advanceAmount">Advance Amount</label>
          <input name="advanceAmount" required class="form-control form-white" id="advanceAmount" placeholder="Advance Amount" />
        </div>


        <hr>

        <div class="form-group">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save changes</button>
          <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Close</button>
        </div>

        {{ Form::close() }}

      </div>
      <div class="modal-footer">
      </div>

    </div>
  </div>
</div>


@endsection
@section('extra_scripts')
  <script>
      $(document).ready(function() {

        $('#datatable-responsive').DataTable({
        	 "pageLength": 50
        });

      });
      setTimeout(function() {
            $('#alert_message').fadeOut('fast');
        }, 5000);
    </script>
@endsection